### ISSUE TITLE
	Two different characters have the same voice

### ISSUE THREAD

**Issue by cary-rowen** [Mahmood-Taghavi/SAPI_Unifier#1]
The situation after running the software is as mentioned in the title.
"Microsoft Yaoyao - Chinese (Simplified, PRC)" and "Microsoft Kangkang - Chinese (Simplified, PRC)" in the voice list, 
But I'm pretty sure that their voices are exactly the same.
From the beginning to the end, only "Yaoyao" was speaking, Even if I set it to "Kangkang".
The operating environment is as follows:
1.  System: Windows 10Ver1909 (64Bit) build 18363.778.
2.  Language: Simplified Chinese.
3.  ScreenReader: NVDA2019.3.1.
4.  Has it been tested in software other than NVDA: Yes.

**Comment by Mahmood-Taghavi** [comment]
You are correct both voices are the same.
I check the windows registry for Kangkang one-Core voice and found its "VoicePath" entry refers to Yaoyao voice. Please note the problem is not from SAPI_Unifier. By the way thanks to your comment  I provided the following registry fix:
[Kangkang.zip](https://github.com/Mahmood-Taghavi/SAPI_Unifier/files/4548440/Kangkang.zip)

**Comment by cary-rowen** [comment]
Oh, Thank you for your patience.
What is the specific reason? Does this error have anything to do with SAPI_Unifier?
Thanks.

**Comment by cary-rowen** [comment]
@Mahmood-Taghavi Is the cause of this issue from Windows? Can you integrate your registry patch entry into
SAPI_Unifier?

**Comment by Mahmood-Taghavi** [comment]
Dear Cary-Rowen,
Please use the provided registry file to fix the problem.
I prefer not to define a separate rule for this voice in my program because the registry setting of this voice may change by Microsoft in the future. Hence, implementing a separate rule for just this voice may cause bigger problems.
